### ISSUE TITLE
/var/sldata is empty

### ISSUE THREAD

**Issue by KlavsKlavsen** [Tekki/docker-sql-ledger#1]
When I build for aarch64, and use the docker-compose file in this project to run it - /var/sldata is empty (I did: docker exec -it sl-app /bin/bash to investigate
/var/www/sql-ledger/images is a symlink to /var/sldata/images - which does not exist - hence images is not shown.

the entrypoint script does not seem to generate /var/sldata - yet the readme of this project says /var/sldata is generated.. ?

**Comment by Tekki** [comment]
It should work now. If you still have problems please reopen this issue.

By the way: `css` is no longer part of `sldata`.
